add error handling to script

diff --git a/root/custom-services.d/meloday b/root/custom-services.d/meloday
--- a/root/custom-services.d/meloday
+++ b/root/custom-services.d/meloday
@@ -1,10 +1,13 @@
 #!/usr/bin/with-contenv bash
 ### Default values
-sleepInterval='3m'
+sleepInterval='1m'
 
-log "Running meloday..."
+echo "Running meloday..."
 # run py script
-python /app/meloday.py -c
+if ! python /app/meloday.py -c; then
+  echo "Error: meloday.py failed to execute." >&2
+  exit 1
+fi
 
-log "Meloday run Complete. Sleeping for ${sleepInterval}."
+echo "Meloday run Complete. Sleeping for ${sleepInterval}."
 sleep ${sleepInterval}
